# ==========================================
#  HyperClock Configuration
#  Plugin Version: 1.0.0
#  Config Version: 1.0.0
# ==========================================

# Currently this changes will only take effect AFTER a server restart. We are planning on adding a reload command.

# General settings
general:
  prefix: "§9§l[Hyper§d§lClock] §7| " # Remember to keep the last space to make sure there is room between your prefix and message.
  language: "en"

# Update settings
updates:
  auto-update-check: true

  # Who gets the  update notification?
  # Possible values:
  # EVERYONE   -> Everyone will receive the notification.
  # OPS        -> Only server operators
  # PERMISSION -> Only players with the admin permission (hyperclock.admin)! This perm is also by default applied to OP's.
  # NONE       -> Nobody gets the notification except the console.
  notify-type: PERMISSION

# ==========================================
# Stopwatch Settings (Count Up)
# ==========================================
stopwatch:
  enabled: true

  # Should the stopwatch start automatically when the server starts?
  auto-start: false

  # Broadcast settings
  # (Broadcast is currently not available. This will be available later.)
  # (The broadcast messages can be edited inside the lang file of your choice)
  #broadcast:
  #  on-start: true # NOT WORKING
  #  on-stop: true # NOT WORKING
  #  on-reset: false # NOT WORKING

# ==========================================
# Timer Settings (Count Down)
# ==========================================
timer:
  enabled: true

  # Default time. You van manually set your time using the /timer set command.
  # Possible values:
  # ("TIME")   -> Values like "1h", "1m" or "1s". You can also combine these: "1h1m1s".
  # null       -> This will disable the feature. Make sure to remove the quotes (use null not "null").
  default-time: "5m"

  # Should the timer start automatically when the server starts?
  # (This will only work if a default time has been set.)
  auto-start: false

  # Broadcast settings
  # (Broadcast is currently not available. This will be available later.)
  # (The broadcast messages can be edited inside the lang file of your choice.)
  # (The on finish broadcast can be toggled inside the on-finish block below.)
  #broadcast:
  #  on-start: true # NOT WORKING
  #  on-stop: true # NOT WORKING
  #  on-set: false # NOT WORKING

  # What will happen if the timer finishes.
  # (on-finish is currently not available. This will be available later.)
  # (The broadcast message can be edited inside the lang file of your choice.)
  #on-finish:
  #  broadcast: true # NOT WORKING
  #  play-sound: true # NOT WORKING
  #  sound: "ENTITY_PLAYER_LEVELUP" # NOT WORKING
  #  execute-commands:
  #    - "give @a apple 1" # NOT WORKING

# ==========================================
# Storage
# ==========================================
storage:
  # Where will the information be stored?
  # Possible values:
  # MEMORY     -> Stores data in RAM. Fast and simple, but lost after restart.
  # FILE       -> NOT AVAILABLE Stores data on disk. Persistent after restart.

  type: "MEMORY" # Currently only memory is available

# ==========================================
# Messages
# ==========================================.

# You can edit the messages in the files inside the lang folder, and you must set the correct language at the top of the config file.